# Generated by Django 2.2.10 on 2020-03-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplySong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('vote_count', models.IntegerField(default=0)),
                ('play_link', models.CharField(max_length=255, null=True)),
                ('cover_complete', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
