# Generated by Django 2.2.10 on 2020-03-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applysong',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='applysong',
            table='apply_song',
        ),
    ]
