# Generated by Django 2.2.10 on 2020-04-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20200329_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(db_index=True, max_length=40)),
                ('user_agent', models.CharField(max_length=255)),
                ('create_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vote_limit',
                'managed': True,
            },
        ),
    ]
